### ISSUE TITLE
Cardinality of role not checked correctly

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#75] opened 2017-07-28 15:15 UTC
`    ASSOCIATION Dokument_Grundnutzung =`
`    Dokument (EXTERNAL) -<#> {0..1}  SO_Nutzungsplanung_20170105.Rechtsvorschriften.Dokument;`    
`    Grundnutzung -- {1..*} Grundnutzung;`    
`    END Dokument_Grundnutzung;`    

All the `Grundnutzung`-Objects in the attached XTF are not associated with a `Dokument`.
[roh_20170717A.zip](https://github.com/claeis/ilivalidator/files/1183482/roh_20170717A.zip)

**Comment by claeis** [comment] 2017-08-08 06:38
EXTERNAL indicates that the referenced objects are in a different basket (even outside of the same file). The validator doesn't know, that he has access to all objects, therefore he assumes that these references reference objects to which he has no access. He can not check the cardinality or that the object even exists.

**Comment by claeis** [comment] 2017-08-08 06:40
see #78

**Comment by edigonzales** [comment] 2017-09-06 08:01
From my point of view it still (v.1.4.0) does not complain about the `Grundnutzungs`-Objects not associated with `Document`-Objects.

**Comment by claeis** [comment] 2017-12-04 10:31
duplicate of #92
fixed in 1.6.0

**Closed by claeis** 2017-12-04 10:31 UTC
