### ISSUE TITLE
Behaviour with large ITF files

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilivalidator#26] opened 2017-01-28 14:59 UTC
Not sure if it's an issue. 

[https://data.geo.admin.ch/ch.swisstopo-vd.amtliche-vermessung/DM01AVCH24D/ITF/BS/2701.zip](https://data.geo.admin.ch/ch.swisstopo-vd.amtliche-vermessung/DM01AVCH24D/ITF/BS/2701.zip)

macOS Sierra / Oracle Java 1.8: Hangs while validating.

Ubuntu 16.04 / Oracle Java 1.8: Finishes validation.

Ubuntu 16.04 / Oracle Java 1.8 with -Xmx2048m: 

`Info: read(): Linienelement... (ItfReader.java:237)
Error: GC overhead limit exceeded
Error:     java.util.Arrays.copyOfRange(Arrays.java:3664)
Error:     java.lang.String.<init>(String.java:207)
Error:     java.lang.StringBuilder.toString(StringBuilder.java:407)
Error:     ch.interlis.ili2c.metamodel.PrecisionDecimal.layoutChars(PrecisionDecimal.java:153)
Error:     ch.interlis.ili2c.metamodel.PrecisionDecimal.toString(PrecisionDecimal.java:109)
Error:     ch.interlis.iox_j.validator.Validator.validateNumericType(Validator.java:1876)
Error:     ch.interlis.iox_j.validator.Validator.validateCoordType(Validator.java:1768)
Error:     ch.interlis.iox_j.validator.Validator.validatePolyline(Validator.java:1742)
Error:     ch.interlis.iox_j.validator.Validator.validateAttrValue(Validator.java:1542)
Error:     ch.interlis.iox_j.validator.Validator.validateObject(Validator.java:1197)
Error:     ch.interlis.iox_j.validator.Validator.validate(Validator.java:171)
Error:     org.interlis2.validator.Validator.runValidation(Validator.java:135)
Error:     org.interlis2.validator.Main.main(Main.java:114)
Info: ...validation failed
`

**Comment by claeis** [comment] 2017-02-20 19:32
duplicate of #18

**Closed by claeis** 2017-02-20 19:32 UTC
